# Generated by Django 4.2.2 on 2023-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_delete_teacherinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="sex",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
