# Generated by Django 4.2.2 on 2023-06-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_userinfo_sex"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="sex",),
    ]
