# Generated by Django 4.2.2 on 2023-06-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_remove_userinfo_sex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentinfo", old_name="name", new_name="title",
        ),
    ]
