# Generated by Django 4.2.2 on 2023-06-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0010_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameModel(old_name="CourseInfo", new_name="UserInfo",),
    ]
