# Generated by Django 4.2.2 on 2023-06-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0015_user_delete_studentinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
