# Generated by Django 4.2.2 on 2023-06-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0018_courseinfo_enroll_status_courseinfo_gpa_condition_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="courseinfo", name="enroll_status",),
        migrations.RemoveField(model_name="courseinfo", name="gpa_condition",),
        migrations.RemoveField(model_name="courseinfo", name="level_condition",),
    ]
