# Generated by Django 4.2.2 on 2023-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0019_remove_courseinfo_enroll_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="enroll_status",
            field=models.CharField(
                choices=[("open", "开放选课"), ("closed", "已关闭选课"), ("pending", "待定")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="gpa_condition",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="level_condition",
            field=models.CharField(
                choices=[
                    ("freshman", "大一"),
                    ("sophomore", "大二"),
                    ("junior", "大三"),
                    ("senior", "大四"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
