# Generated by Django 4.2.2 on 2023-06-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0020_userinfo_enroll_status_userinfo_gpa_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="Course_Type",
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
