# Generated by Django 4.2.2 on 2023-06-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0029_remove_userinfo_type_userinfo_coursetype"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="CourseType",),
        migrations.AddField(
            model_name="userinfo",
            name="Course_Type",
            field=models.CharField(default="1", max_length=50),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="enroll_status",
            field=models.CharField(
                choices=[("开放", "开放选课"), ("关闭", "已关闭选课"), ("待定", "待定")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="level_condition",
            field=models.CharField(
                choices=[("大一", "大一"), ("大二", "大二"), ("大三", "大三"), ("大四", "大四")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
