# Generated by Django 4.2.2 on 2023-06-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0031_alter_userinfo_course_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="Course_Type",),
    ]
