# Generated by Django 4.2.2 on 2023-06-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0034_remove_userinfo_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="Course_Type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
