# Generated by Django 4.2.2 on 2023-06-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0035_userinfo_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="time",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
